const PATH = {
  ENCOUNTER: 'ENCOUNTER',
  ENCOUNTER_BATTLE: 'ENCOUNTER_BATTLE',
  ENCOUNTER_MONSTER: 'ENCOUNTER_MONSTER',
  ENCOUNTER_REST: 'ENCOUNTER_REST',
  ENCOUNTER_REWARD: 'ENCOUNTER_REWARD',
  ENCOUNTERS_NEW: 'ENCOUNTERS_NEW',
  HOME: 'HOME',
  NPCS_NEW: 'NPCS_NEW',
  NPC_EDIT: 'NPC_EDIT',
  NPCS_INDEX: 'NPCS_INDEX',
  SESSION: 'SESSION',
  SESSION_EDIT: 'SESSION_EDIT',
  SESSION_ENCOUNTERS: 'SESSION_ENCOUNTERS',
  SESSION_PLAYERS: 'SESSION_PLAYERS',
  SESSION_REWARD: 'SESSION_REWARD',
  SESSIONS: 'SESSIONS',
  SESSIONS_NEW: 'SESSIONS_NEW',
  SIGNIN: 'SIGNIN',
  SIGNUP: 'SIGNUP',
};


export default PATH;
